### ISSUE TITLE
训练数据是否会开放？

### ISSUE THREAD

**Issue by myweihp** [openmedlab/PULSE#1]
感谢你们的工作！
> 大规模训练：PULSE模型使用约4,000,000个中文医学领域和通用领域的指令微调数据进行进一步调优。

请问相关训练数据有开源的打算吗？此外，模型支持的最大输入长度是多少呢？

**Comment by myweihp** [comment]
另外，Elo评测能否加上[HuatuoGPT](https://github.com/FreedomIntelligence/HuatuoGPT)呢？

**Comment by zhangxiaofan101** [comment]
> 

你好，我们暂时没有计划开源训练数据。
目前已开源的PULSE模型最大输入长度为2048，事实上，我们有更长输入长度、更大模型以及量化后的版本。
如果您对此有兴趣，欢迎合作。

**Comment by myweihp** [comment]
好的，谢谢！
